version: '3'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - 5432:5432
  app:
    build:
      context: .
    command: --wait-for-db-and-migrate
    ports:
      - 8090:8080
    links:
      - db
    environment:
      DB_ENDPOINT_ADDRESS: db
      DB_PORT: 5432
      DB_NAME: app
      spring.datasource.username: app
      spring.datasource.password: pass
