version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  app:
    build:
      context: .
    ports:
      - 8090:8080
    links:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://db/